### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by rpavlick** [sharvil/api-docs#1]
1. Closed api-docs tab 

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [api-docs](https://github.com/sharvil/api-docs) package, v0.0.1

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:604

Error: Pane has been destroyed
  at Pane.module.exports.Pane.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:604:15)
  at Pane.module.exports.Pane.focus (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:193:21)
  at atom-pane.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane-element.js:59:23)
  at atom-pane.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane-element.js:61:18)
  at atom-pane.PaneElement.activated (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane-element.js:125:19)
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:612:27)
  at PaneContainer.module.exports.PaneContainer.activateNextPane (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane-container.js:272:26)
  at Pane.module.exports.Pane.destroyed (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:627:24)
  at Pane.module.exports.Model.destroy (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/model.js:45:58)
  at Pane.module.exports.Pane.destroy (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:620:39)
  at DocView.destroy (/Users/rpavlick/.atom/packages/api-docs/src/doc_view.js:75:18)
  at Pane.module.exports.Pane.destroyItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:444:18)
  at HTMLDivElement.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:195:22)
  at space-pen-ul.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  2x -8:41.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:41.3.0 api-docs:search-under-cursor (atom-text-editor.editor.is-focused)
  2x -6:48.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:47.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -1:37 core:delete (ul.list-inline.tab-bar.inset-panel)
     -1:34.7.0 api-docs:search-under-cursor (atom-text-editor.editor.is-focused)
     -1:29.4.0 find-and-replace:show (div.api-docs-doc)
  5x -1:27.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:25.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:25 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:24.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:23.1.0 core:delete (ul.list-inline.tab-bar.inset-panel)
     -0:21.5.0 api-docs:search-under-cursor (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "api-docs": {
    "css": false,
    "dom_events": false,
    "dom": false,
    "html": false,
    "http": false,
    "javascript": false,
    "python": true
  }
}
```

### Installed Packages

```coffee
# User
api-docs, vundefined
git-projects, v1.14.1
language-fortran, v1.5.6
language-idl, v0.2.0
language-julia, v0.9.0
language-matlab, v0.1.1
language-r, v0.2.0
linter, v0.12.6
linter-shellcheck, v0.0.8
linter-write-good, v0.4.3

# Dev
No dev packages
```

**Comment by sharvil** [comment]
@rpavlick, is this reproducible or was it a one-off?

**Comment by rpavlick** [comment]
I can't reproduce it now. I'll close the issue.
