### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by febimauro** [sharvil/api-docs#38]
I have this error when call apidoc by press ctrl+i (i have change this because of ctrld non worked) in a window. the help works but these error window give problem of editing
please 

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: Unknown Windows Version
**Thrown From**: [api-docs](https://github.com/sharvil/api-docs) package, v0.0.6

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\provs\.atom\packages\api-docs\src\query_view.js:69

TypeError: Cannot read property 'length' of undefined
    at QueryView.getIcon_ (file:///C:/Users/provs/.atom/packages/api-docs/src/query_view.js:69:24)
    at QueryView.viewForItem (file:///C:/Users/provs/.atom/packages/api-docs/src/query_view.js:26:17)
    at QueryView.module.exports.SelectListView.populateList (C:\Users\provs\.atom\packages\api-docs\node_modules\atom-space-pen-views\lib\select-list-view.js:206:29)
    at QueryView.module.exports.SelectListView.setItems (C:\Users\provs\.atom\packages\api-docs\node_modules\atom-space-pen-views\lib\select-list-view.js:167:12)
    at new QueryView (file:///C:/Users/provs/.atom/packages/api-docs/src/query_view.js:20:10)
    at Application.searchUnderCursor_ (file:///C:/Users/provs/.atom/packages/api-docs/src/main.js:45:5)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\provs\AppData\Local\atom\app-1.12.5\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\provs\AppData\Local\atom\app-1.12.5\resources\app.asar\src\command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\provs\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\provs\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\provs\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\provs\AppData\Local\atom\app-1.12.5\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\provs\AppData\Local\atom\app-1.12.5\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\provs\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\provs\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\provs\AppData\Local\atom\app-1.12.5\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\provs\AppData\Local\atom\app-1.12.5\resources\app.asar\src\window-event-handler.js:3:59)
```

### Commands

```
 15x -3:05.9.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:17.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:15.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:13.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.4.0 api-docs:search-under-cursor (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  },
  "api-docs": {
    "cpp": true
  }
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.6 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by ychow** [comment]
same problem with me....

**Comment by Staberinde** [comment]
This seems to be caused by invalid JSON in one of the `db.json` files in subdirectories of `.atom/api-docs/data/` To figure out which one, try opening chrome debugger and breaking on `.atom\packages\api-docs\src\query_view.js:69`, you should be able to figure out by the item in question which database file  is invalid. Try deselecting the corresponding language and restarting atom. It should get cleared out by the garbage collector and then redownloaded when you reselect it. If this doesn't work just delete the `db.json` file itself before deselecting, restarting and reselecting
