### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by edgerunner** [sharvil/api-docs#4]
### Steps to reproduce

1. Trigger the `Search Under Cursor` command from the Settings pane.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [api-docs](https://github.com/sharvil/api-docs) package, v0.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Users/mert/.atom/packages/api-docs/src/main.js:41

TypeError: Cannot read property 'getGrammar' of undefined
  at Application.searchUnderCursor_ (/Users/mert/.atom/packages/api-docs/src/main.js:41:27)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:08.4.0 command-palette:toggle (div.settings-view.pane-item)
     -0:03.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 api-docs:search-under-cursor (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {},
  "api-docs": {
    "node": true,
    "git": true,
    "coffeescript": true,
    "npm": true,
    "ruby": true,
    "rails": true,
    "svg": true
  }
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.1
browser-refresh, v0.9.0
pigments, v0.8.1
svg-preview, v0.6.0

# Dev
No dev packages
```

**Comment by sharvil** [comment]
Thanks for reporting!
